import { route } from "@/common/config/route";

export type GlobalSearchCategory = {
  id: "centers" | "doctors" | "labs";
  label: string;
  description: string;
  route: string;
};

export const GLOBAL_SEARCH_CATEGORIES: GlobalSearchCategory[] = [
  {
    id: "centers",
    label: "Health Centers",
    description: "Hospitals, clinics, and care hubs across Kashmir",
    route: route.findCenters.path,
  },
  {
    id: "doctors",
    label: "Doctors",
    description: "Specialists verified by JK Health Care AI",
    route: route.doctors.path,
  },
  {
    id: "labs",
    label: "Lab Tests",
    description: "Diagnostics, home sample collection, and reports",
    route: route.labTests.path,
  },
];

export const GLOBAL_SEARCH_LOCATIONS = [
  "Srinagar",
  "Anantnag",
  "Baramulla",
  "Kupwara",
  "Pulwama",
  "Kulgam",
  "Shopian",
  "Bandipora",
  "Ganderbal",
  "Budgam",
  "Handwara",
  "Sopore",
  "Tral",
  "Awantipora",
  "Pampore",
  "Qazigund",
  "Bijbehara",
  "Pahalgam",
  "Uri",
  "Tangmarg",
  "Gulmarg",
  "Chadoora",
  "Charar-e-Sharief",
  "Magam",
  "Kreeri",
  "Kunzer",
  "Sumbal",
  "Hajin",
  "Lolab",
  "Karnah",
  "Trehgam",
  "Kralpora",
  "Devsar",
  "Qaimoh",
  "Dooru",
  "Kokernag",
  "Mattan",
  "Aishmuqam",
  "Achabal",
  "Rajpora",
  "Lassipora",
  "Kakapora",
  "Pattan",
  "Beerwah",
  "Khansahib",
  "Kangan",
] as const;

export const GLOBAL_SEARCH_FEATURES = [
  "General Physician",
  "Family Medicine Specialist",
  "General Practitioner",
  "Internal Medicine Specialist",
  "Pediatrician",
  "Neonatologist",
  "Pediatric Surgeon",
  "Gynecologist",
  "Obstetrician",
  "Infertility Specialist",
  "Reproductive Endocrinologist",
  "IVF Specialist",
  "Fetal Medicine Specialist",
  "Cardiologist",
  "Interventional Cardiologist",
  "Cardiothoracic Surgeon",
  "Vascular Surgeon",
  "Neurologist",
  "Neurosurgeon",
  "Pediatric Neurologist",
  "Neuropsychiatrist",
  "Orthopedic Surgeon",
  "Spine Surgeon",
  "Sports Medicine Specialist",
  "Rheumatologist",
  "Physiotherapist",
  "Pulmonologist",
  "Thoracic Surgeon",
  "Sleep Medicine Specialist",
  "Gastroenterologist",
  "Hepatologist",
  "Gastrointestinal Surgeon",
  "Nephrologist",
  "Urologist",
  "Andrologist",
  "Endocrinologist",
  "Diabetologist",
  "Ophthalmologist",
  "Cataract Surgeon",
  "Cornea Specialist",
  "Retina Specialist",
  "Glaucoma Specialist",
  "Oculoplastic Surgeon",
  "Pediatric Ophthalmologist",
  "ENT Specialist",
  "Audiologist",
  "Cochlear Implant Surgeon",
  "Head and Neck Surgeon",
  "Dentist",
  "Orthodontist",
  "Endodontist",
  "Prosthodontist",
  "Periodontist",
  "Oral and Maxillofacial Surgeon",
  "Pedodontist",
  "Dermatologist",
  "Trichologist",
  "Hair Transplant Surgeon",
  "Cosmetologist",
  "Plastic and Reconstructive Surgeon",
  "Aesthetic Surgeon",
  "Laser Specialist",
  "Psychiatrist",
  "Psychologist",
  "Clinical Psychologist",
  "Sexologist",
  "Addiction Specialist",
  "Oncologist",
  "Surgical Oncologist",
  "Medical Oncologist",
  "Radiation Oncologist",
  "Hemato-Oncologist",
  "Pediatric Oncologist",
  "Radiologist",
  "Pathologist",
  "Microbiologist",
  "Biochemist",
  "Nuclear Medicine Specialist",
  "Emergency Medicine Specialist",
  "Critical Care Specialist",
  "Intensivist",
  "Trauma Surgeon",
  "Immunologist",
  "Allergist",
  "Hematologist",
  "Geneticist",
  "Pain Management Specialist",
  "Palliative Care Specialist",
  "Occupational Therapist",
  "Speech Therapist",
  "Dietitian",
  "Nutritionist",
  "Geriatric Specialist",
  "Public Health Specialist",
  "Epidemiologist",
  "Tropical Medicine Specialist",
  "Forensic Medicine Specialist",
  "Anesthesiologist",
  "Bariatric Surgeon",
  "Transplant Surgeon",
  "Laparoscopic Surgeon",
  "Reconstructive Surgeon",
  "Sleep Specialist",
  "Preventive Medicine Specialist",
  "Neurointerventional Radiologist",
  "Epileptologist",
  "Movement Disorder Specialist",
  "Pain and Palliative Neurologist",
  "Electrophysiologist",
  "Heart Failure Specialist",
  "Pediatric Cardiologist",
  "Interventional Pulmonologist",
  "ECMO Specialist",
  "Bone Marrow Transplant Specialist",
  "Radiation Physicist",
  "Hand Surgeon",
  "Foot and Ankle Surgeon",
  "Pediatric Orthopedic Surgeon",
  "Colorectal Surgeon",
  "Pancreatic Surgeon",
  "Metabolic Specialist",
  "Clinical Geneticist",
  "Genomic Medicine Specialist",
  "Molecular Oncologist",
  "Neuro-Ophthalmologist",
  "Ocular Oncologist",
  "Oral Pathologist",
  "Oral Radiologist",
  "Dental Implantologist",
  "Aesthetic Dermatologist",
  "Laser and Cosmetic Dermatologist",
  "Tattoo Removal Specialist",
  "Occupational Medicine Specialist",
  "Sports Physiotherapist",
  "Neurorehabilitation Specialist",
  "Speech and Swallow Therapist",
  "Clinical Pathologist",
  "Immunohematologist",
  "Cytopathologist",
  "Pediatric Endocrinologist",
  "Pediatric Nephrologist",
  "Pediatric Gastroenterologist",
  "Developmental Pediatrician",
  "Urogynecologist",
  "Gynecologic Oncologist",
  "Maternal-Fetal Medicine Specialist",
  "Transfusion Medicine Specialist",
  "Occupational Health Specialist",
  "Aerospace Medicine Specialist",
  "Disaster Medicine Specialist",
  "Telemedicine and Digital Health Specialist",
] as const;

export const GLOBAL_SEARCH_PLACEHOLDERS = [
  "Search trusted doctors",
  "Find nearby labs",
  "Discover emergency care",
  "Book AI voice consultations",
  "Locate 24/7 pharmacies",
] as const;
